### ISSUE TITLE
Meaning of concatenate x and labels when generating

### ISSUE THREAD

**Issue by yyccli** [DegardinBruno/Kinetic-GAN#2]
Hi, thanks again for your work~
I now have some questions on the operations in **Generator** where you concatenate the input noise *z* and the *embedded action label* to form the real input *x*, as you can see in generator.py line 80 and 81. The discriminator tries to distinguish the fake skeletons from the real ones, and if we do not concatenate the *embedded action label*, our generator will also try to generate actions like reals so the discriminator may fail, so i think if we just input the noise *z*, the network will still try to generate actions like the reals. The action label is something like a signal that let we people know what action we want, but for the network, it will learn it implicitly. I am really not sure about this, so i am wondering what is the meaning of concatenating the input noise *z* and the *embedded action label*.
Looking forward to your reply! Many Thanks.

**Comment by DegardinBruno** [comment]
Hey @yyccli, thank you for your interest in the codebase.
Yes, using Kinetic-GAN by just giving a latent point z to the generator, it will still learn to generate actions but unconditionally, where we do not have control over what action we want to generate.
However, class labels as additional information to a GAN result in significant improvements in the subjective quality of the samples generated by the model, mainly caused by giving the training process valuable clues that help with optimization.
Learning to predict the action label (in both generator and discriminator) would definitely work as an alternative to giving apriori information about the action class.
Tell me if I wasn't clear, and let me know if you have any further questions!!

**Comment by yyccli** [comment]
Hi, thanks for you reply!
I'm starting to understand what you said, and it's becoming clearer for me now.
