### ISSUE TITLE
Confusion with some terminologies of the Paper

### ISSUE THREAD

**Issue by akashghimireOfficial** [DegardinBruno/Kinetic-GAN#7]
Hello,
I am an undergraduate studying synthetic Action Pose generation. While I was reading your paper I came through some terminologies which I can't understand.  In  (3.1)  Graph Convolutional Networks Preliminaries of the paper I came across terminologies such as:
1) Graph Resolution Layer(L)
2) Partition strategy P

So, from what I have understood "L" means how many Nodes and edges are in the Graph but I am not sure if I am correct or not. 
And for "P" I can't understand it. So could you please give me some explanation?

**Comment by DegardinBruno** [comment]
Hello @akashghimireOfficial!

> So, from what I have understood "L" means how many Nodes and edges are in the Graph but I am not sure if I am correct or not.

Yes, exactly! You can relate "Graph Resolution" to "Image Resolution" (on conventional GANs), where instead of more or fewer pixels, you have more or fewer nodes (and corresponding edges).

> And for "P" I can't understand it. So could you please give me some explanation?

The Partition Strategy is related to the graph convolution operator. Again relating to images with convolutions, instead of having a kernel size where you have a "root" pixel with its neighbour pixels around it, you have a graph partition. The partition strategy here is defined by the "root" node with the corresponding neighbour/connected nodes.
You can check Fig. 3 of this [paper (ST-GCN)](https://arxiv.org/abs/1801.07455), which is illustrated nicely.

**Comment by akashghimireOfficial** [comment]
Thank you for your reply. After your reply, I went through the original Paper of (ST-GCN) and your code. After reading the paper multiple times I feel I have some understanding of code on this GitHub. However, I still have some confusion:
1) In this GitHub, in tgcn.py there is the term: **torch.einsum('nkctv,kvw->nctw', (x, A))** and i want to map this equation to the  equations in ST-GCN.  So, is it related to Eqn 5 or Eqn 10 from the paper ST-GCN. 
2) Where are the Eqn 5 and Eqn 10 of the paper ST-GCN paper used in this repository?

I hope i am not asking a lot of questions. But I also wanted to understand about the paper and code at the same time so it is important to understand it.

**Comment by DegardinBruno** [comment]
Hello @akashghimireOfficial,

Eq.5 and Eq.10 are theoretically the same. The only thing that changes is the neighbour normalization terms (Z in 5 and degree matrix Λ in 10).
The [Einstein Summation](https://pytorch.org/docs/stable/generated/torch.einsum.html) is notation based, meaning that the order in which you insert the dimensions (n,k,c,t,v) and tensors matter defining different operations. 

`x = torch.einsum('nkctv,kvw->nctw', (x, A))` means:

![53620316-783d7800-3c2d-11e9-8b3f-6322a921f0d9](https://user-images.githubusercontent.com/61987997/168445865-4873f6fa-ad3e-4adf-96ef-ce5c6164837f.png)
